# Generated by Django 2.0.1 on 2018-06-12 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BestThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['gambler'],
            },
        ),
        migrations.CreateModel(
            name='Bet1X2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['match', 'gambler'],
            },
        ),
        migrations.CreateModel(
            name='BetScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gambler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='GoalKingBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Gambler')),
            ],
            options={
                'ordering': ['gambler'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiID', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('position', models.CharField(max_length=48)),
                ('goals', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['team', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.PositiveIntegerField(null=True)),
                ('away', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiID', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=48)),
                ('crestUrl', models.URLField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.Group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='awayTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awayMatch', to='bets.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='homeTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeMatch', to='bets.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Score'),
        ),
        migrations.AddField(
            model_name='goalkingbet',
            name='goalKing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Player'),
        ),
        migrations.AddField(
            model_name='betscore',
            name='gambler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Gambler'),
        ),
        migrations.AddField(
            model_name='betscore',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Match'),
        ),
        migrations.AddField(
            model_name='betscore',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Score'),
        ),
        migrations.AddField(
            model_name='bet1x2',
            name='gambler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Gambler'),
        ),
        migrations.AddField(
            model_name='bet1x2',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Match'),
        ),
        migrations.AddField(
            model_name='bestthree',
            name='first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='bets.Team'),
        ),
        migrations.AddField(
            model_name='bestthree',
            name='gambler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Gambler'),
        ),
        migrations.AddField(
            model_name='bestthree',
            name='second',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='bets.Team'),
        ),
        migrations.AddField(
            model_name='bestthree',
            name='third',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third', to='bets.Team'),
        ),
    ]
